### ISSUE TITLE
`undefined` use

### ISSUE THREAD

**Issue by 9point6** [bbc/morph-doctor#10]
https://github.com/bbc/morph-doctor/blob/master/test/clinics/ports.spec.ts#L22

In this file you seem to be using the `undefined` variable where my understanding was it should be generally avoided in JS due to it being an unreserved keyword in non-global scopes: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined

This might just be a typescript-ism I'm not familiar with though.

**Comment by benwainwright** [comment]
Lol; I'd always assumed `undefined` was a keyword, not a property. Bloody JavaScript.

if you agree that this is something we should do, then we should have `no-undefined` turned on in `eslint-config-fabl`

**Comment by benwainwright** [comment]
Resolved in 55dcb72103c1ee4dcc12f8901ff7d324edd92da6
