### ISSUE TITLE
Could change module resolution `webpack.config.js`

### ISSUE THREAD

**Issue by MattLongCode** [bbc/morph-doctor#3]
Could change module resolution `webpack.config.js`
```
  resolve: {
    extensions: [".webpack.js", ".web.js", ".ts", ".js"]
  },
```
to:
```
  resolve: {
    extensions: [".ts"]
  },
```
so that `.ts` modules are resolved first. Can only see `.ts` modules so the others are probably not needed atm.

**Comment by benwainwright** [comment]
The intention is for there only to ever be ts
