### ISSUE TITLE
Cheeky refactors

### ISSUE THREAD

**Issue by 9point6** [bbc/morph-doctor#6]
* https://github.com/bbc/morph-doctor/blob/master/lib/clinics/ports.ts#L10-L74
  - This function is a bit of a beefy mountain range, can we break it up into smaller functions please!

(may probably add more here)

**Comment by benwainwright** [comment]
Fair enough. Will do...

**Comment by benwainwright** [comment]
Resolved here: f47d56bf0fc7d5770f67df6eb674845c211c7ffd
