### ISSUE TITLE
Test fixtures

### ISSUE THREAD

**Issue by 9point6** [bbc/morph-doctor#9]
https://github.com/bbc/morph-doctor/blob/master/test/clinics/certLocations.spec.ts#L10-L41

Not a big fan of inlining chunky fixtures like this, could we break them out?

Though this is pretty benign, so feel free to WontFix this!

**Comment by benwainwright** [comment]
See your point; but I don't think this is "chunky" enough to warrent it. Extra files is still more structural complexity.
